version: '3'

services:
  server: 
    build: ./api
    expose:
        - ${APP_SERVER_PORT}
    environment: 
        API_HOST: ${API_HOST}
        APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports: 
        - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
        - ./api:/srv/app/server
    links: 
        - db
  client:
    build: ./client
    environment: 
        - VUE_APP_PORT=${VUE_APP_PORT}
    expose:
        - ${VUE_APP_PORT}
    ports: 
        - ${VUE_APP_PORT}:${VUE_APP_PORT}
    volumes:
        - ./client:/srv/app/client
    links:
        - server
  db:
    image: mysql
    restart: always
    expose:
        - "3306"
    volumes:
        - ./db_data:/home
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: abes
        MYSQL_PASSWORD: pass1234
        MYSQL_DATABASE: abes_pnqs
